<?php
/*
 * SpaceTradersAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpaceTradersAPILib\Tests;

use SpaceTradersAPILib\Exceptions\ApiException;
use SpaceTradersAPILib\Exceptions;
use SpaceTradersAPILib\ApiHelper;
use SpaceTradersAPILib\Models;
use PHPUnit\Framework\TestCase;

class ShipyardsControllerTest extends TestCase
{
    /**
     * @var \SpaceTradersAPILib\Controllers\ShipyardsController Controller instance
     */
    protected static $controller;

    /**
     * @var HttpCallBackCatcher Callback
     */
    protected static $httpResponse;

    /**
     * Setup test class
     */
    public static function setUpBeforeClass(): void
    {
        self::$httpResponse = new HttpCallBackCatcher();
        self::$controller = ClientFactory::create(self::$httpResponse)->getShipyardsController();
    }


    /**
     * Purchase a ship
     */
    public function testTestPostMyShips()
    {
        // Parameters for the API call
        $body = null;

        // Set callback and perform API call
        $result = null;
        try {
            $result = self::$controller->postMyShips($body);
        } catch (ApiException $e) {
        }

        // Test response code
        $this->assertEquals(
            200,
            self::$httpResponse->getResponse()->getStatusCode(),
            "Status is not 200"
        );

        // Test headers
        $headers = [];
        $headers['Content-Type'] = 'application/json' ;
        
        $this->assertTrue(
            TestHelper::areHeadersProperSubsetOf($headers, self::$httpResponse->getResponse()->getHeaders(), true),
            "Headers do not match"
        );
    }
}
