# -*- coding: utf-8 -*-

"""
spacetradersapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

import json
import dateutil.parser

from tests.controllers.controller_test_base import ControllerTestBase
from tests.test_helper import TestHelper
from spacetradersapi.api_helper import APIHelper
from spacetradersapi.models.my_ships_request import MyShipsRequest


class ShipyardsControllerTests(ControllerTestBase):

    @classmethod
    def setUpClass(cls):
        super(ShipyardsControllerTests, cls).setUpClass()
        cls.controller = cls.client.shipyards
        cls.response_catcher = cls.controller.http_call_back

    # Purchase a ship
    def test_post_my_ships(self):
        # Parameters for the API call
        body = None

        # Perform the API call through the SDK function
        result = self.controller.post_my_ships(body)

        # Test response code
        self.assertEquals(self.response_catcher.response.status_code, 200)

        # Test headers
        expected_headers = {}
        expected_headers['content-type'] = 'application/json'

        self.assertTrue(TestHelper.match_headers(expected_headers, self.response_catcher.response.headers))


