# -*- coding: utf-8 -*-

"""
spacetradersapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from spacetradersapi.models.myield import Yield
import os
from spacetradersapi.utilities.schema_validator_wrapper import SchemaValidatorWrapper
from jsonschema import ValidationError
from spacetradersapi.api_helper import APIHelper


class Extraction(object):

    """Implementation of the 'Extraction' model.

    TODO: type model description here.

    Attributes:
        ship_symbol (string): TODO: type description here.
        myield (Yield): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "ship_symbol": 'shipSymbol',
        "myield": 'yield'
    }

    def __init__(self,
                 ship_symbol=None,
                 myield=None):
        """Constructor for the Extraction class"""

        # Initialize members of the class
        self.ship_symbol = ship_symbol
        self.myield = myield

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary

        ship_symbol = dictionary.get('shipSymbol')
        myield = Yield.from_dictionary(dictionary.get('yield')) if dictionary.get('yield') else None
        # Return an object of this model
        return cls(ship_symbol,
                   myield)

    @classmethod
    def validate(cls, val):
        """Validates value against class schema

        Args:
            val: the value to be validated

        Returns:
            boolean : if value is valid against schema.

        """
        return SchemaValidatorWrapper.getValidator(APIHelper.get_schema_path(os.path.abspath(__file__))).is_valid(val)
