# -*- coding: utf-8 -*-

"""
spacetradersapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
import os
from spacetradersapi.utilities.schema_validator_wrapper import SchemaValidatorWrapper
from jsonschema import ValidationError
from spacetradersapi.api_helper import APIHelper


class Meta(object):

    """Implementation of the 'Meta' model.

    TODO: type model description here.

    Attributes:
        total (int): TODO: type description here.
        page (int): TODO: type description here.
        limit (int): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "total": 'total',
        "page": 'page',
        "limit": 'limit'
    }

    def __init__(self,
                 total=None,
                 page=None,
                 limit=None):
        """Constructor for the Meta class"""

        # Initialize members of the class
        self.total = total
        self.page = page
        self.limit = limit

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary

        total = dictionary.get('total')
        page = dictionary.get('page')
        limit = dictionary.get('limit')
        # Return an object of this model
        return cls(total,
                   page,
                   limit)

    @classmethod
    def validate(cls, val):
        """Validates value against class schema

        Args:
            val: the value to be validated

        Returns:
            boolean : if value is valid against schema.

        """
        return SchemaValidatorWrapper.getValidator(APIHelper.get_schema_path(os.path.abspath(__file__))).is_valid(val)
