# -*- coding: utf-8 -*-

"""
spacetradersapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
import os
from spacetradersapi.utilities.schema_validator_wrapper import SchemaValidatorWrapper
from jsonschema import ValidationError
from spacetradersapi.api_helper import APIHelper


class ShipyardListing(object):

    """Implementation of the 'ShipyardListing' model.

    TODO: type model description here.

    Attributes:
        id (string): TODO: type description here.
        waypoint (string): TODO: type description here.
        price (int): TODO: type description here.
        role (string): TODO: type description here.
        frame (string): TODO: type description here.
        reactor (string): TODO: type description here.
        engine (string): TODO: type description here.
        modules (list of string): TODO: type description here.
        mounts (list of string): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "id": 'id',
        "waypoint": 'waypoint',
        "price": 'price',
        "role": 'role',
        "frame": 'frame',
        "reactor": 'reactor',
        "engine": 'engine',
        "modules": 'modules',
        "mounts": 'mounts'
    }

    def __init__(self,
                 id=None,
                 waypoint=None,
                 price=None,
                 role=None,
                 frame=None,
                 reactor=None,
                 engine=None,
                 modules=None,
                 mounts=None):
        """Constructor for the ShipyardListing class"""

        # Initialize members of the class
        self.id = id
        self.waypoint = waypoint
        self.price = price
        self.role = role
        self.frame = frame
        self.reactor = reactor
        self.engine = engine
        self.modules = modules
        self.mounts = mounts

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary

        id = dictionary.get('id')
        waypoint = dictionary.get('waypoint')
        price = dictionary.get('price')
        role = dictionary.get('role')
        frame = dictionary.get('frame')
        reactor = dictionary.get('reactor')
        engine = dictionary.get('engine')
        modules = dictionary.get('modules')
        mounts = dictionary.get('mounts')
        # Return an object of this model
        return cls(id,
                   waypoint,
                   price,
                   role,
                   frame,
                   reactor,
                   engine,
                   modules,
                   mounts)

    @classmethod
    def validate(cls, val):
        """Validates value against class schema

        Args:
            val: the value to be validated

        Returns:
            boolean : if value is valid against schema.

        """
        return SchemaValidatorWrapper.getValidator(APIHelper.get_schema_path(os.path.abspath(__file__))).is_valid(val)
