# -*- coding: utf-8 -*-

"""
spacetradersapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from spacetradersapi.models.deliver import Deliver
from spacetradersapi.models.payment import Payment
import os
from spacetradersapi.utilities.schema_validator_wrapper import SchemaValidatorWrapper
from jsonschema import ValidationError
from spacetradersapi.api_helper import APIHelper


class Terms(object):

    """Implementation of the 'Terms' model.

    TODO: type model description here.

    Attributes:
        deadline (string): TODO: type description here.
        payment (Payment): TODO: type description here.
        deliver (list of Deliver): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "deadline": 'deadline',
        "payment": 'payment',
        "deliver": 'deliver'
    }

    def __init__(self,
                 deadline=None,
                 payment=None,
                 deliver=None):
        """Constructor for the Terms class"""

        # Initialize members of the class
        self.deadline = deadline
        self.payment = payment
        self.deliver = deliver

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary

        deadline = dictionary.get('deadline')
        payment = Payment.from_dictionary(dictionary.get('payment')) if dictionary.get('payment') else None
        deliver = None
        if dictionary.get('deliver') is not None:
            deliver = [Deliver.from_dictionary(x) for x in dictionary.get('deliver')]
        # Return an object of this model
        return cls(deadline,
                   payment,
                   deliver)

    @classmethod
    def validate(cls, val):
        """Validates value against class schema

        Args:
            val: the value to be validated

        Returns:
            boolean : if value is valid against schema.

        """
        return SchemaValidatorWrapper.getValidator(APIHelper.get_schema_path(os.path.abspath(__file__))).is_valid(val)
