/*
 * SpaceTradersAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package io.spacetraders.alpha.v200.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for AgentsResponse type.
 */
public class AgentsResponse {
    private Data1 data;

    /**
     * Default constructor.
     */
    public AgentsResponse() {
    }

    /**
     * Initialization constructor.
     * @param  data  Data1 value for data.
     */
    public AgentsResponse(
            Data1 data) {
        this.data = data;
    }

    /**
     * Getter for Data.
     * @return Returns the Data1
     */
    @JsonGetter("data")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Data1 getData() {
        return data;
    }

    /**
     * Setter for Data.
     * @param data Value for Data1
     */
    @JsonSetter("data")
    public void setData(Data1 data) {
        this.data = data;
    }

    /**
     * Converts this AgentsResponse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "AgentsResponse [" + "data=" + data + "]";
    }

    /**
     * Builds a new {@link AgentsResponse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link AgentsResponse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .data(getData());
        return builder;
    }

    /**
     * Class to build instances of {@link AgentsResponse}.
     */
    public static class Builder {
        private Data1 data;



        /**
         * Setter for data.
         * @param  data  Data1 value for data.
         * @return Builder
         */
        public Builder data(Data1 data) {
            this.data = data;
            return this;
        }

        /**
         * Builds a new {@link AgentsResponse} object using the set fields.
         * @return {@link AgentsResponse}
         */
        public AgentsResponse build() {
            return new AgentsResponse(data);
        }
    }
}
