/*
 * SpaceTradersAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package io.spacetraders.alpha.v200.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;

/**
 * This is a model class for Data2 type.
 */
public class Data2 {
    private List<String> submitted;

    /**
     * Default constructor.
     */
    public Data2() {
    }

    /**
     * Initialization constructor.
     * @param  submitted  List of String value for submitted.
     */
    public Data2(
            List<String> submitted) {
        this.submitted = submitted;
    }

    /**
     * Getter for Submitted.
     * @return Returns the List of String
     */
    @JsonGetter("submitted")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<String> getSubmitted() {
        return submitted;
    }

    /**
     * Setter for Submitted.
     * @param submitted Value for List of String
     */
    @JsonSetter("submitted")
    public void setSubmitted(List<String> submitted) {
        this.submitted = submitted;
    }

    /**
     * Converts this Data2 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Data2 [" + "submitted=" + submitted + "]";
    }

    /**
     * Builds a new {@link Data2.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Data2.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .submitted(getSubmitted());
        return builder;
    }

    /**
     * Class to build instances of {@link Data2}.
     */
    public static class Builder {
        private List<String> submitted;



        /**
         * Setter for submitted.
         * @param  submitted  List of String value for submitted.
         * @return Builder
         */
        public Builder submitted(List<String> submitted) {
            this.submitted = submitted;
            return this;
        }

        /**
         * Builds a new {@link Data2} object using the set fields.
         * @return {@link Data2}
         */
        public Data2 build() {
            return new Data2(submitted);
        }
    }
}
