/*
 * SpaceTradersAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package io.spacetraders.alpha.v200.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;

/**
 * This is a model class for Data18 type.
 */
public class Data18 {
    private List<MarketTrade> exports;
    private List<MarketTrade> imports;
    private List<MarketTrade> exchange;

    /**
     * Default constructor.
     */
    public Data18() {
    }

    /**
     * Initialization constructor.
     * @param  exports  List of MarketTrade value for exports.
     * @param  imports  List of MarketTrade value for imports.
     * @param  exchange  List of MarketTrade value for exchange.
     */
    public Data18(
            List<MarketTrade> exports,
            List<MarketTrade> imports,
            List<MarketTrade> exchange) {
        this.exports = exports;
        this.imports = imports;
        this.exchange = exchange;
    }

    /**
     * Getter for Exports.
     * @return Returns the List of MarketTrade
     */
    @JsonGetter("exports")
    public List<MarketTrade> getExports() {
        return exports;
    }

    /**
     * Setter for Exports.
     * @param exports Value for List of MarketTrade
     */
    @JsonSetter("exports")
    public void setExports(List<MarketTrade> exports) {
        this.exports = exports;
    }

    /**
     * Getter for Imports.
     * @return Returns the List of MarketTrade
     */
    @JsonGetter("imports")
    public List<MarketTrade> getImports() {
        return imports;
    }

    /**
     * Setter for Imports.
     * @param imports Value for List of MarketTrade
     */
    @JsonSetter("imports")
    public void setImports(List<MarketTrade> imports) {
        this.imports = imports;
    }

    /**
     * Getter for Exchange.
     * @return Returns the List of MarketTrade
     */
    @JsonGetter("exchange")
    public List<MarketTrade> getExchange() {
        return exchange;
    }

    /**
     * Setter for Exchange.
     * @param exchange Value for List of MarketTrade
     */
    @JsonSetter("exchange")
    public void setExchange(List<MarketTrade> exchange) {
        this.exchange = exchange;
    }

    /**
     * Converts this Data18 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Data18 [" + "exports=" + exports + ", imports=" + imports + ", exchange=" + exchange
                + "]";
    }

    /**
     * Builds a new {@link Data18.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Data18.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(exports, imports, exchange);
        return builder;
    }

    /**
     * Class to build instances of {@link Data18}.
     */
    public static class Builder {
        private List<MarketTrade> exports;
        private List<MarketTrade> imports;
        private List<MarketTrade> exchange;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  exports  List of MarketTrade value for exports.
         * @param  imports  List of MarketTrade value for imports.
         * @param  exchange  List of MarketTrade value for exchange.
         */
        public Builder(List<MarketTrade> exports, List<MarketTrade> imports,
                List<MarketTrade> exchange) {
            this.exports = exports;
            this.imports = imports;
            this.exchange = exchange;
        }

        /**
         * Setter for exports.
         * @param  exports  List of MarketTrade value for exports.
         * @return Builder
         */
        public Builder exports(List<MarketTrade> exports) {
            this.exports = exports;
            return this;
        }

        /**
         * Setter for imports.
         * @param  imports  List of MarketTrade value for imports.
         * @return Builder
         */
        public Builder imports(List<MarketTrade> imports) {
            this.imports = imports;
            return this;
        }

        /**
         * Setter for exchange.
         * @param  exchange  List of MarketTrade value for exchange.
         * @return Builder
         */
        public Builder exchange(List<MarketTrade> exchange) {
            this.exchange = exchange;
            return this;
        }

        /**
         * Builds a new {@link Data18} object using the set fields.
         * @return {@link Data18}
         */
        public Data18 build() {
            return new Data18(exports, imports, exchange);
        }
    }
}
