/*
 * SpaceTradersAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package io.spacetraders.alpha.v200.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;

/**
 * This is a model class for Data13 type.
 */
public class Data13 {
    private List<ScannedShip> ships;
    private Cooldown cooldown;

    /**
     * Default constructor.
     */
    public Data13() {
    }

    /**
     * Initialization constructor.
     * @param  ships  List of ScannedShip value for ships.
     * @param  cooldown  Cooldown value for cooldown.
     */
    public Data13(
            List<ScannedShip> ships,
            Cooldown cooldown) {
        this.ships = ships;
        this.cooldown = cooldown;
    }

    /**
     * Getter for Ships.
     * @return Returns the List of ScannedShip
     */
    @JsonGetter("ships")
    public List<ScannedShip> getShips() {
        return ships;
    }

    /**
     * Setter for Ships.
     * @param ships Value for List of ScannedShip
     */
    @JsonSetter("ships")
    public void setShips(List<ScannedShip> ships) {
        this.ships = ships;
    }

    /**
     * Getter for Cooldown.
     * @return Returns the Cooldown
     */
    @JsonGetter("cooldown")
    public Cooldown getCooldown() {
        return cooldown;
    }

    /**
     * Setter for Cooldown.
     * @param cooldown Value for Cooldown
     */
    @JsonSetter("cooldown")
    public void setCooldown(Cooldown cooldown) {
        this.cooldown = cooldown;
    }

    /**
     * Converts this Data13 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Data13 [" + "ships=" + ships + ", cooldown=" + cooldown + "]";
    }

    /**
     * Builds a new {@link Data13.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Data13.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(ships, cooldown);
        return builder;
    }

    /**
     * Class to build instances of {@link Data13}.
     */
    public static class Builder {
        private List<ScannedShip> ships;
        private Cooldown cooldown;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  ships  List of ScannedShip value for ships.
         * @param  cooldown  Cooldown value for cooldown.
         */
        public Builder(List<ScannedShip> ships, Cooldown cooldown) {
            this.ships = ships;
            this.cooldown = cooldown;
        }

        /**
         * Setter for ships.
         * @param  ships  List of ScannedShip value for ships.
         * @return Builder
         */
        public Builder ships(List<ScannedShip> ships) {
            this.ships = ships;
            return this;
        }

        /**
         * Setter for cooldown.
         * @param  cooldown  Cooldown value for cooldown.
         * @return Builder
         */
        public Builder cooldown(Cooldown cooldown) {
            this.cooldown = cooldown;
            return this;
        }

        /**
         * Builds a new {@link Data13} object using the set fields.
         * @return {@link Data13}
         */
        public Data13 build() {
            return new Data13(ships, cooldown);
        }
    }
}
