/*
 * SpaceTradersAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package io.spacetraders.alpha.v200.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for Data17 type.
 */
public class Data17 {
    private Ship ship;
    private Integer credits;

    /**
     * Default constructor.
     */
    public Data17() {
    }

    /**
     * Initialization constructor.
     * @param  ship  Ship value for ship.
     * @param  credits  Integer value for credits.
     */
    public Data17(
            Ship ship,
            Integer credits) {
        this.ship = ship;
        this.credits = credits;
    }

    /**
     * Getter for Ship.
     * @return Returns the Ship
     */
    @JsonGetter("ship")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Ship getShip() {
        return ship;
    }

    /**
     * Setter for Ship.
     * @param ship Value for Ship
     */
    @JsonSetter("ship")
    public void setShip(Ship ship) {
        this.ship = ship;
    }

    /**
     * Getter for Credits.
     * @return Returns the Integer
     */
    @JsonGetter("credits")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getCredits() {
        return credits;
    }

    /**
     * Setter for Credits.
     * @param credits Value for Integer
     */
    @JsonSetter("credits")
    public void setCredits(Integer credits) {
        this.credits = credits;
    }

    /**
     * Converts this Data17 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Data17 [" + "ship=" + ship + ", credits=" + credits + "]";
    }

    /**
     * Builds a new {@link Data17.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Data17.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .ship(getShip())
                .credits(getCredits());
        return builder;
    }

    /**
     * Class to build instances of {@link Data17}.
     */
    public static class Builder {
        private Ship ship;
        private Integer credits;



        /**
         * Setter for ship.
         * @param  ship  Ship value for ship.
         * @return Builder
         */
        public Builder ship(Ship ship) {
            this.ship = ship;
            return this;
        }

        /**
         * Setter for credits.
         * @param  credits  Integer value for credits.
         * @return Builder
         */
        public Builder credits(Integer credits) {
            this.credits = credits;
            return this;
        }

        /**
         * Builds a new {@link Data17} object using the set fields.
         * @return {@link Data17}
         */
        public Data17 build() {
            return new Data17(ship, credits);
        }
    }
}
