/*
 * SpaceTradersAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package io.spacetraders.alpha.v200.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for Extraction type.
 */
public class Extraction {
    private String shipSymbol;
    private Yield yield;

    /**
     * Default constructor.
     */
    public Extraction() {
    }

    /**
     * Initialization constructor.
     * @param  shipSymbol  String value for shipSymbol.
     * @param  yield  Yield value for yield.
     */
    public Extraction(
            String shipSymbol,
            Yield yield) {
        this.shipSymbol = shipSymbol;
        this.yield = yield;
    }

    /**
     * Getter for ShipSymbol.
     * @return Returns the String
     */
    @JsonGetter("shipSymbol")
    public String getShipSymbol() {
        return shipSymbol;
    }

    /**
     * Setter for ShipSymbol.
     * @param shipSymbol Value for String
     */
    @JsonSetter("shipSymbol")
    public void setShipSymbol(String shipSymbol) {
        this.shipSymbol = shipSymbol;
    }

    /**
     * Getter for Yield.
     * @return Returns the Yield
     */
    @JsonGetter("yield")
    public Yield getYield() {
        return yield;
    }

    /**
     * Setter for Yield.
     * @param yield Value for Yield
     */
    @JsonSetter("yield")
    public void setYield(Yield yield) {
        this.yield = yield;
    }

    /**
     * Converts this Extraction into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Extraction [" + "shipSymbol=" + shipSymbol + ", yield=" + yield + "]";
    }

    /**
     * Builds a new {@link Extraction.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Extraction.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(shipSymbol, yield);
        return builder;
    }

    /**
     * Class to build instances of {@link Extraction}.
     */
    public static class Builder {
        private String shipSymbol;
        private Yield yield;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  shipSymbol  String value for shipSymbol.
         * @param  yield  Yield value for yield.
         */
        public Builder(String shipSymbol, Yield yield) {
            this.shipSymbol = shipSymbol;
            this.yield = yield;
        }

        /**
         * Setter for shipSymbol.
         * @param  shipSymbol  String value for shipSymbol.
         * @return Builder
         */
        public Builder shipSymbol(String shipSymbol) {
            this.shipSymbol = shipSymbol;
            return this;
        }

        /**
         * Setter for yield.
         * @param  yield  Yield value for yield.
         * @return Builder
         */
        public Builder yield(Yield yield) {
            this.yield = yield;
            return this;
        }

        /**
         * Builds a new {@link Extraction} object using the set fields.
         * @return {@link Extraction}
         */
        public Extraction build() {
            return new Extraction(shipSymbol, yield);
        }
    }
}
