/*
 * SpaceTradersAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package io.spacetraders.alpha.v200.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for MarketTrade type.
 */
public class MarketTrade {
    private String waypointSymbol;
    private String tradeSymbol;
    private int price;
    private int tariff;

    /**
     * Default constructor.
     */
    public MarketTrade() {
    }

    /**
     * Initialization constructor.
     * @param  waypointSymbol  String value for waypointSymbol.
     * @param  tradeSymbol  String value for tradeSymbol.
     * @param  price  int value for price.
     * @param  tariff  int value for tariff.
     */
    public MarketTrade(
            String waypointSymbol,
            String tradeSymbol,
            int price,
            int tariff) {
        this.waypointSymbol = waypointSymbol;
        this.tradeSymbol = tradeSymbol;
        this.price = price;
        this.tariff = tariff;
    }

    /**
     * Getter for WaypointSymbol.
     * @return Returns the String
     */
    @JsonGetter("waypointSymbol")
    public String getWaypointSymbol() {
        return waypointSymbol;
    }

    /**
     * Setter for WaypointSymbol.
     * @param waypointSymbol Value for String
     */
    @JsonSetter("waypointSymbol")
    public void setWaypointSymbol(String waypointSymbol) {
        this.waypointSymbol = waypointSymbol;
    }

    /**
     * Getter for TradeSymbol.
     * @return Returns the String
     */
    @JsonGetter("tradeSymbol")
    public String getTradeSymbol() {
        return tradeSymbol;
    }

    /**
     * Setter for TradeSymbol.
     * @param tradeSymbol Value for String
     */
    @JsonSetter("tradeSymbol")
    public void setTradeSymbol(String tradeSymbol) {
        this.tradeSymbol = tradeSymbol;
    }

    /**
     * Getter for Price.
     * @return Returns the int
     */
    @JsonGetter("price")
    public int getPrice() {
        return price;
    }

    /**
     * Setter for Price.
     * @param price Value for int
     */
    @JsonSetter("price")
    public void setPrice(int price) {
        this.price = price;
    }

    /**
     * Getter for Tariff.
     * @return Returns the int
     */
    @JsonGetter("tariff")
    public int getTariff() {
        return tariff;
    }

    /**
     * Setter for Tariff.
     * @param tariff Value for int
     */
    @JsonSetter("tariff")
    public void setTariff(int tariff) {
        this.tariff = tariff;
    }

    /**
     * Converts this MarketTrade into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "MarketTrade [" + "waypointSymbol=" + waypointSymbol + ", tradeSymbol=" + tradeSymbol
                + ", price=" + price + ", tariff=" + tariff + "]";
    }

    /**
     * Builds a new {@link MarketTrade.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link MarketTrade.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(waypointSymbol, tradeSymbol, price, tariff);
        return builder;
    }

    /**
     * Class to build instances of {@link MarketTrade}.
     */
    public static class Builder {
        private String waypointSymbol;
        private String tradeSymbol;
        private int price;
        private int tariff;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  waypointSymbol  String value for waypointSymbol.
         * @param  tradeSymbol  String value for tradeSymbol.
         * @param  price  int value for price.
         * @param  tariff  int value for tariff.
         */
        public Builder(String waypointSymbol, String tradeSymbol, int price, int tariff) {
            this.waypointSymbol = waypointSymbol;
            this.tradeSymbol = tradeSymbol;
            this.price = price;
            this.tariff = tariff;
        }

        /**
         * Setter for waypointSymbol.
         * @param  waypointSymbol  String value for waypointSymbol.
         * @return Builder
         */
        public Builder waypointSymbol(String waypointSymbol) {
            this.waypointSymbol = waypointSymbol;
            return this;
        }

        /**
         * Setter for tradeSymbol.
         * @param  tradeSymbol  String value for tradeSymbol.
         * @return Builder
         */
        public Builder tradeSymbol(String tradeSymbol) {
            this.tradeSymbol = tradeSymbol;
            return this;
        }

        /**
         * Setter for price.
         * @param  price  int value for price.
         * @return Builder
         */
        public Builder price(int price) {
            this.price = price;
            return this;
        }

        /**
         * Setter for tariff.
         * @param  tariff  int value for tariff.
         * @return Builder
         */
        public Builder tariff(int tariff) {
            this.tariff = tariff;
            return this;
        }

        /**
         * Builds a new {@link MarketTrade} object using the set fields.
         * @return {@link MarketTrade}
         */
        public MarketTrade build() {
            return new MarketTrade(waypointSymbol, tradeSymbol, price, tariff);
        }
    }
}
