/*
 * SpaceTradersAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package io.spacetraders.alpha.v200.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for MyAgentResponse type.
 */
public class MyAgentResponse {
    private Agent data;

    /**
     * Default constructor.
     */
    public MyAgentResponse() {
    }

    /**
     * Initialization constructor.
     * @param  data  Agent value for data.
     */
    public MyAgentResponse(
            Agent data) {
        this.data = data;
    }

    /**
     * Getter for Data.
     * @return Returns the Agent
     */
    @JsonGetter("data")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Agent getData() {
        return data;
    }

    /**
     * Setter for Data.
     * @param data Value for Agent
     */
    @JsonSetter("data")
    public void setData(Agent data) {
        this.data = data;
    }

    /**
     * Converts this MyAgentResponse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "MyAgentResponse [" + "data=" + data + "]";
    }

    /**
     * Builds a new {@link MyAgentResponse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link MyAgentResponse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .data(getData());
        return builder;
    }

    /**
     * Class to build instances of {@link MyAgentResponse}.
     */
    public static class Builder {
        private Agent data;



        /**
         * Setter for data.
         * @param  data  Agent value for data.
         * @return Builder
         */
        public Builder data(Agent data) {
            this.data = data;
            return this;
        }

        /**
         * Builds a new {@link MyAgentResponse} object using the set fields.
         * @return {@link MyAgentResponse}
         */
        public MyAgentResponse build() {
            return new MyAgentResponse(data);
        }
    }
}
