/*
 * SpaceTradersAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package io.spacetraders.alpha.v200.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for MyShipsJumpResponse type.
 */
public class MyShipsJumpResponse {
    private Data10 data;

    /**
     * Default constructor.
     */
    public MyShipsJumpResponse() {
    }

    /**
     * Initialization constructor.
     * @param  data  Data10 value for data.
     */
    public MyShipsJumpResponse(
            Data10 data) {
        this.data = data;
    }

    /**
     * Getter for Data.
     * @return Returns the Data10
     */
    @JsonGetter("data")
    public Data10 getData() {
        return data;
    }

    /**
     * Setter for Data.
     * @param data Value for Data10
     */
    @JsonSetter("data")
    public void setData(Data10 data) {
        this.data = data;
    }

    /**
     * Converts this MyShipsJumpResponse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "MyShipsJumpResponse [" + "data=" + data + "]";
    }

    /**
     * Builds a new {@link MyShipsJumpResponse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link MyShipsJumpResponse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(data);
        return builder;
    }

    /**
     * Class to build instances of {@link MyShipsJumpResponse}.
     */
    public static class Builder {
        private Data10 data;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  data  Data10 value for data.
         */
        public Builder(Data10 data) {
            this.data = data;
        }

        /**
         * Setter for data.
         * @param  data  Data10 value for data.
         * @return Builder
         */
        public Builder data(Data10 data) {
            this.data = data;
            return this;
        }

        /**
         * Builds a new {@link MyShipsJumpResponse} object using the set fields.
         * @return {@link MyShipsJumpResponse}
         */
        public MyShipsJumpResponse build() {
            return new MyShipsJumpResponse(data);
        }
    }
}
