/*
 * SpaceTradersAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package io.spacetraders.alpha.v200.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for MyShipsNavigateResponse1 type.
 */
public class MyShipsNavigateResponse1 {
    private Data16 data;

    /**
     * Default constructor.
     */
    public MyShipsNavigateResponse1() {
    }

    /**
     * Initialization constructor.
     * @param  data  Data16 value for data.
     */
    public MyShipsNavigateResponse1(
            Data16 data) {
        this.data = data;
    }

    /**
     * Getter for Data.
     * @return Returns the Data16
     */
    @JsonGetter("data")
    public Data16 getData() {
        return data;
    }

    /**
     * Setter for Data.
     * @param data Value for Data16
     */
    @JsonSetter("data")
    public void setData(Data16 data) {
        this.data = data;
    }

    /**
     * Converts this MyShipsNavigateResponse1 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "MyShipsNavigateResponse1 [" + "data=" + data + "]";
    }

    /**
     * Builds a new {@link MyShipsNavigateResponse1.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link MyShipsNavigateResponse1.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(data);
        return builder;
    }

    /**
     * Class to build instances of {@link MyShipsNavigateResponse1}.
     */
    public static class Builder {
        private Data16 data;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  data  Data16 value for data.
         */
        public Builder(Data16 data) {
            this.data = data;
        }

        /**
         * Setter for data.
         * @param  data  Data16 value for data.
         * @return Builder
         */
        public Builder data(Data16 data) {
            this.data = data;
            return this;
        }

        /**
         * Builds a new {@link MyShipsNavigateResponse1} object using the set fields.
         * @return {@link MyShipsNavigateResponse1}
         */
        public MyShipsNavigateResponse1 build() {
            return new MyShipsNavigateResponse1(data);
        }
    }
}
