/*
 * SpaceTradersAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package io.spacetraders.alpha.v200.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for MyShipsOrbitResponse type.
 */
public class MyShipsOrbitResponse {
    private Data4 data;

    /**
     * Default constructor.
     */
    public MyShipsOrbitResponse() {
    }

    /**
     * Initialization constructor.
     * @param  data  Data4 value for data.
     */
    public MyShipsOrbitResponse(
            Data4 data) {
        this.data = data;
    }

    /**
     * Getter for Data.
     * @return Returns the Data4
     */
    @JsonGetter("data")
    public Data4 getData() {
        return data;
    }

    /**
     * Setter for Data.
     * @param data Value for Data4
     */
    @JsonSetter("data")
    public void setData(Data4 data) {
        this.data = data;
    }

    /**
     * Converts this MyShipsOrbitResponse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "MyShipsOrbitResponse [" + "data=" + data + "]";
    }

    /**
     * Builds a new {@link MyShipsOrbitResponse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link MyShipsOrbitResponse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(data);
        return builder;
    }

    /**
     * Class to build instances of {@link MyShipsOrbitResponse}.
     */
    public static class Builder {
        private Data4 data;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  data  Data4 value for data.
         */
        public Builder(Data4 data) {
            this.data = data;
        }

        /**
         * Setter for data.
         * @param  data  Data4 value for data.
         * @return Builder
         */
        public Builder data(Data4 data) {
            this.data = data;
            return this;
        }

        /**
         * Builds a new {@link MyShipsOrbitResponse} object using the set fields.
         * @return {@link MyShipsOrbitResponse}
         */
        public MyShipsOrbitResponse build() {
            return new MyShipsOrbitResponse(data);
        }
    }
}
