/*
 * SpaceTradersAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package io.spacetraders.alpha.v200.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.spacetraders.alpha.v200.models.containers.MyShipsScanResponseData;

/**
 * This is a model class for MyShipsScanResponse type.
 */
public class MyShipsScanResponse {
    private MyShipsScanResponseData data;

    /**
     * Default constructor.
     */
    public MyShipsScanResponse() {
    }

    /**
     * Initialization constructor.
     * @param  data  MyShipsScanResponseData value for data.
     */
    public MyShipsScanResponse(
            MyShipsScanResponseData data) {
        this.data = data;
    }

    /**
     * Getter for Data.
     * @return Returns the MyShipsScanResponseData
     */
    @JsonGetter("data")
    public MyShipsScanResponseData getData() {
        return data;
    }

    /**
     * Setter for Data.
     * @param data Value for MyShipsScanResponseData
     */
    @JsonSetter("data")
    public void setData(MyShipsScanResponseData data) {
        this.data = data;
    }

    /**
     * Converts this MyShipsScanResponse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "MyShipsScanResponse [" + "data=" + data + "]";
    }

    /**
     * Builds a new {@link MyShipsScanResponse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link MyShipsScanResponse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(data);
        return builder;
    }

    /**
     * Class to build instances of {@link MyShipsScanResponse}.
     */
    public static class Builder {
        private MyShipsScanResponseData data;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  data  MyShipsScanResponseData value for data.
         */
        public Builder(MyShipsScanResponseData data) {
            this.data = data;
        }

        /**
         * Setter for data.
         * @param  data  MyShipsScanResponseData value for data.
         * @return Builder
         */
        public Builder data(MyShipsScanResponseData data) {
            this.data = data;
            return this;
        }

        /**
         * Builds a new {@link MyShipsScanResponse} object using the set fields.
         * @return {@link MyShipsScanResponse}
         */
        public MyShipsScanResponse build() {
            return new MyShipsScanResponse(data);
        }
    }
}
