/*
 * SpaceTradersAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package io.spacetraders.alpha.v200.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;

/**
 * This is a model class for MyShipsResponse1 type.
 */
public class MyShipsResponse1 {
    private List<Ship> data;
    private Meta meta;

    /**
     * Default constructor.
     */
    public MyShipsResponse1() {
    }

    /**
     * Initialization constructor.
     * @param  data  List of Ship value for data.
     * @param  meta  Meta value for meta.
     */
    public MyShipsResponse1(
            List<Ship> data,
            Meta meta) {
        this.data = data;
        this.meta = meta;
    }

    /**
     * Getter for Data.
     * @return Returns the List of Ship
     */
    @JsonGetter("data")
    public List<Ship> getData() {
        return data;
    }

    /**
     * Setter for Data.
     * @param data Value for List of Ship
     */
    @JsonSetter("data")
    public void setData(List<Ship> data) {
        this.data = data;
    }

    /**
     * Getter for Meta.
     * @return Returns the Meta
     */
    @JsonGetter("meta")
    public Meta getMeta() {
        return meta;
    }

    /**
     * Setter for Meta.
     * @param meta Value for Meta
     */
    @JsonSetter("meta")
    public void setMeta(Meta meta) {
        this.meta = meta;
    }

    /**
     * Converts this MyShipsResponse1 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "MyShipsResponse1 [" + "data=" + data + ", meta=" + meta + "]";
    }

    /**
     * Builds a new {@link MyShipsResponse1.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link MyShipsResponse1.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(data, meta);
        return builder;
    }

    /**
     * Class to build instances of {@link MyShipsResponse1}.
     */
    public static class Builder {
        private List<Ship> data;
        private Meta meta;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  data  List of Ship value for data.
         * @param  meta  Meta value for meta.
         */
        public Builder(List<Ship> data, Meta meta) {
            this.data = data;
            this.meta = meta;
        }

        /**
         * Setter for data.
         * @param  data  List of Ship value for data.
         * @return Builder
         */
        public Builder data(List<Ship> data) {
            this.data = data;
            return this;
        }

        /**
         * Setter for meta.
         * @param  meta  Meta value for meta.
         * @return Builder
         */
        public Builder meta(Meta meta) {
            this.meta = meta;
            return this;
        }

        /**
         * Builds a new {@link MyShipsResponse1} object using the set fields.
         * @return {@link MyShipsResponse1}
         */
        public MyShipsResponse1 build() {
            return new MyShipsResponse1(data, meta);
        }
    }
}
