/*
 * SpaceTradersAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package io.spacetraders.alpha.v200.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for MyShipsDeliverResponse type.
 */
public class MyShipsDeliverResponse {
    private ContractDelivery data;

    /**
     * Default constructor.
     */
    public MyShipsDeliverResponse() {
    }

    /**
     * Initialization constructor.
     * @param  data  ContractDelivery value for data.
     */
    public MyShipsDeliverResponse(
            ContractDelivery data) {
        this.data = data;
    }

    /**
     * Getter for Data.
     * @return Returns the ContractDelivery
     */
    @JsonGetter("data")
    public ContractDelivery getData() {
        return data;
    }

    /**
     * Setter for Data.
     * @param data Value for ContractDelivery
     */
    @JsonSetter("data")
    public void setData(ContractDelivery data) {
        this.data = data;
    }

    /**
     * Converts this MyShipsDeliverResponse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "MyShipsDeliverResponse [" + "data=" + data + "]";
    }

    /**
     * Builds a new {@link MyShipsDeliverResponse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link MyShipsDeliverResponse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(data);
        return builder;
    }

    /**
     * Class to build instances of {@link MyShipsDeliverResponse}.
     */
    public static class Builder {
        private ContractDelivery data;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  data  ContractDelivery value for data.
         */
        public Builder(ContractDelivery data) {
            this.data = data;
        }

        /**
         * Setter for data.
         * @param  data  ContractDelivery value for data.
         * @return Builder
         */
        public Builder data(ContractDelivery data) {
            this.data = data;
            return this;
        }

        /**
         * Builds a new {@link MyShipsDeliverResponse} object using the set fields.
         * @return {@link MyShipsDeliverResponse}
         */
        public MyShipsDeliverResponse build() {
            return new MyShipsDeliverResponse(data);
        }
    }
}
