/*
 * SpaceTradersAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package io.spacetraders.alpha.v200.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for MyShipsJumpRequest type.
 */
public class MyShipsJumpRequest {
    private String destination;

    /**
     * Default constructor.
     */
    public MyShipsJumpRequest() {
    }

    /**
     * Initialization constructor.
     * @param  destination  String value for destination.
     */
    public MyShipsJumpRequest(
            String destination) {
        this.destination = destination;
    }

    /**
     * Getter for Destination.
     * The system symbol to jump to.
     * @return Returns the String
     */
    @JsonGetter("destination")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getDestination() {
        return destination;
    }

    /**
     * Setter for Destination.
     * The system symbol to jump to.
     * @param destination Value for String
     */
    @JsonSetter("destination")
    public void setDestination(String destination) {
        this.destination = destination;
    }

    /**
     * Converts this MyShipsJumpRequest into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "MyShipsJumpRequest [" + "destination=" + destination + "]";
    }

    /**
     * Builds a new {@link MyShipsJumpRequest.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link MyShipsJumpRequest.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .destination(getDestination());
        return builder;
    }

    /**
     * Class to build instances of {@link MyShipsJumpRequest}.
     */
    public static class Builder {
        private String destination;



        /**
         * Setter for destination.
         * @param  destination  String value for destination.
         * @return Builder
         */
        public Builder destination(String destination) {
            this.destination = destination;
            return this;
        }

        /**
         * Builds a new {@link MyShipsJumpRequest} object using the set fields.
         * @return {@link MyShipsJumpRequest}
         */
        public MyShipsJumpRequest build() {
            return new MyShipsJumpRequest(destination);
        }
    }
}
