/*
 * SpaceTradersAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package io.spacetraders.alpha.v200.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for MyShipsDeliverRequest type.
 */
public class MyShipsDeliverRequest {
    private String contractId;
    private String tradeSymbol;
    private Integer units;

    /**
     * Default constructor.
     */
    public MyShipsDeliverRequest() {
    }

    /**
     * Initialization constructor.
     * @param  contractId  String value for contractId.
     * @param  tradeSymbol  String value for tradeSymbol.
     * @param  units  Integer value for units.
     */
    public MyShipsDeliverRequest(
            String contractId,
            String tradeSymbol,
            Integer units) {
        this.contractId = contractId;
        this.tradeSymbol = tradeSymbol;
        this.units = units;
    }

    /**
     * Getter for ContractId.
     * @return Returns the String
     */
    @JsonGetter("contractId")
    public String getContractId() {
        return contractId;
    }

    /**
     * Setter for ContractId.
     * @param contractId Value for String
     */
    @JsonSetter("contractId")
    public void setContractId(String contractId) {
        this.contractId = contractId;
    }

    /**
     * Getter for TradeSymbol.
     * @return Returns the String
     */
    @JsonGetter("tradeSymbol")
    public String getTradeSymbol() {
        return tradeSymbol;
    }

    /**
     * Setter for TradeSymbol.
     * @param tradeSymbol Value for String
     */
    @JsonSetter("tradeSymbol")
    public void setTradeSymbol(String tradeSymbol) {
        this.tradeSymbol = tradeSymbol;
    }

    /**
     * Getter for Units.
     * @return Returns the Integer
     */
    @JsonGetter("units")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getUnits() {
        return units;
    }

    /**
     * Setter for Units.
     * @param units Value for Integer
     */
    @JsonSetter("units")
    public void setUnits(Integer units) {
        this.units = units;
    }

    /**
     * Converts this MyShipsDeliverRequest into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "MyShipsDeliverRequest [" + "contractId=" + contractId + ", tradeSymbol="
                + tradeSymbol + ", units=" + units + "]";
    }

    /**
     * Builds a new {@link MyShipsDeliverRequest.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link MyShipsDeliverRequest.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(contractId, tradeSymbol)
                .units(getUnits());
        return builder;
    }

    /**
     * Class to build instances of {@link MyShipsDeliverRequest}.
     */
    public static class Builder {
        private String contractId;
        private String tradeSymbol;
        private Integer units;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  contractId  String value for contractId.
         * @param  tradeSymbol  String value for tradeSymbol.
         */
        public Builder(String contractId, String tradeSymbol) {
            this.contractId = contractId;
            this.tradeSymbol = tradeSymbol;
        }

        /**
         * Setter for contractId.
         * @param  contractId  String value for contractId.
         * @return Builder
         */
        public Builder contractId(String contractId) {
            this.contractId = contractId;
            return this;
        }

        /**
         * Setter for tradeSymbol.
         * @param  tradeSymbol  String value for tradeSymbol.
         * @return Builder
         */
        public Builder tradeSymbol(String tradeSymbol) {
            this.tradeSymbol = tradeSymbol;
            return this;
        }

        /**
         * Setter for units.
         * @param  units  Integer value for units.
         * @return Builder
         */
        public Builder units(Integer units) {
            this.units = units;
            return this;
        }

        /**
         * Builds a new {@link MyShipsDeliverRequest} object using the set fields.
         * @return {@link MyShipsDeliverRequest}
         */
        public MyShipsDeliverRequest build() {
            return new MyShipsDeliverRequest(contractId, tradeSymbol, units);
        }
    }
}
