/*
 * SpaceTradersAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package io.spacetraders.alpha.v200.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for MyShipsExtractResponse type.
 */
public class MyShipsExtractResponse {
    private Data6 data;

    /**
     * Default constructor.
     */
    public MyShipsExtractResponse() {
    }

    /**
     * Initialization constructor.
     * @param  data  Data6 value for data.
     */
    public MyShipsExtractResponse(
            Data6 data) {
        this.data = data;
    }

    /**
     * Getter for Data.
     * @return Returns the Data6
     */
    @JsonGetter("data")
    public Data6 getData() {
        return data;
    }

    /**
     * Setter for Data.
     * @param data Value for Data6
     */
    @JsonSetter("data")
    public void setData(Data6 data) {
        this.data = data;
    }

    /**
     * Converts this MyShipsExtractResponse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "MyShipsExtractResponse [" + "data=" + data + "]";
    }

    /**
     * Builds a new {@link MyShipsExtractResponse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link MyShipsExtractResponse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(data);
        return builder;
    }

    /**
     * Class to build instances of {@link MyShipsExtractResponse}.
     */
    public static class Builder {
        private Data6 data;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  data  Data6 value for data.
         */
        public Builder(Data6 data) {
            this.data = data;
        }

        /**
         * Setter for data.
         * @param  data  Data6 value for data.
         * @return Builder
         */
        public Builder data(Data6 data) {
            this.data = data;
            return this;
        }

        /**
         * Builds a new {@link MyShipsExtractResponse} object using the set fields.
         * @return {@link MyShipsExtractResponse}
         */
        public MyShipsExtractResponse build() {
            return new MyShipsExtractResponse(data);
        }
    }
}
