/*
 * SpaceTradersAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package io.spacetraders.alpha.v200.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for Stats type.
 */
public class Stats {
    private int fuelTank;
    private int cargoLimit;
    private int jumpRange;

    /**
     * Default constructor.
     */
    public Stats() {
    }

    /**
     * Initialization constructor.
     * @param  fuelTank  int value for fuelTank.
     * @param  cargoLimit  int value for cargoLimit.
     * @param  jumpRange  int value for jumpRange.
     */
    public Stats(
            int fuelTank,
            int cargoLimit,
            int jumpRange) {
        this.fuelTank = fuelTank;
        this.cargoLimit = cargoLimit;
        this.jumpRange = jumpRange;
    }

    /**
     * Getter for FuelTank.
     * @return Returns the int
     */
    @JsonGetter("fuelTank")
    public int getFuelTank() {
        return fuelTank;
    }

    /**
     * Setter for FuelTank.
     * @param fuelTank Value for int
     */
    @JsonSetter("fuelTank")
    public void setFuelTank(int fuelTank) {
        this.fuelTank = fuelTank;
    }

    /**
     * Getter for CargoLimit.
     * @return Returns the int
     */
    @JsonGetter("cargoLimit")
    public int getCargoLimit() {
        return cargoLimit;
    }

    /**
     * Setter for CargoLimit.
     * @param cargoLimit Value for int
     */
    @JsonSetter("cargoLimit")
    public void setCargoLimit(int cargoLimit) {
        this.cargoLimit = cargoLimit;
    }

    /**
     * Getter for JumpRange.
     * @return Returns the int
     */
    @JsonGetter("jumpRange")
    public int getJumpRange() {
        return jumpRange;
    }

    /**
     * Setter for JumpRange.
     * @param jumpRange Value for int
     */
    @JsonSetter("jumpRange")
    public void setJumpRange(int jumpRange) {
        this.jumpRange = jumpRange;
    }

    /**
     * Converts this Stats into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Stats [" + "fuelTank=" + fuelTank + ", cargoLimit=" + cargoLimit + ", jumpRange="
                + jumpRange + "]";
    }

    /**
     * Builds a new {@link Stats.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Stats.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(fuelTank, cargoLimit, jumpRange);
        return builder;
    }

    /**
     * Class to build instances of {@link Stats}.
     */
    public static class Builder {
        private int fuelTank;
        private int cargoLimit;
        private int jumpRange;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  fuelTank  int value for fuelTank.
         * @param  cargoLimit  int value for cargoLimit.
         * @param  jumpRange  int value for jumpRange.
         */
        public Builder(int fuelTank, int cargoLimit, int jumpRange) {
            this.fuelTank = fuelTank;
            this.cargoLimit = cargoLimit;
            this.jumpRange = jumpRange;
        }

        /**
         * Setter for fuelTank.
         * @param  fuelTank  int value for fuelTank.
         * @return Builder
         */
        public Builder fuelTank(int fuelTank) {
            this.fuelTank = fuelTank;
            return this;
        }

        /**
         * Setter for cargoLimit.
         * @param  cargoLimit  int value for cargoLimit.
         * @return Builder
         */
        public Builder cargoLimit(int cargoLimit) {
            this.cargoLimit = cargoLimit;
            return this;
        }

        /**
         * Setter for jumpRange.
         * @param  jumpRange  int value for jumpRange.
         * @return Builder
         */
        public Builder jumpRange(int jumpRange) {
            this.jumpRange = jumpRange;
            return this;
        }

        /**
         * Builds a new {@link Stats} object using the set fields.
         * @return {@link Stats}
         */
        public Stats build() {
            return new Stats(fuelTank, cargoLimit, jumpRange);
        }
    }
}
