/*
 * SpaceTradersAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package io.spacetraders.alpha.v200.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for SystemsResponse1 type.
 */
public class SystemsResponse1 {
    private System data;

    /**
     * Default constructor.
     */
    public SystemsResponse1() {
    }

    /**
     * Initialization constructor.
     * @param  data  System value for data.
     */
    public SystemsResponse1(
            System data) {
        this.data = data;
    }

    /**
     * Getter for Data.
     * @return Returns the System
     */
    @JsonGetter("data")
    public System getData() {
        return data;
    }

    /**
     * Setter for Data.
     * @param data Value for System
     */
    @JsonSetter("data")
    public void setData(System data) {
        this.data = data;
    }

    /**
     * Converts this SystemsResponse1 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "SystemsResponse1 [" + "data=" + data + "]";
    }

    /**
     * Builds a new {@link SystemsResponse1.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link SystemsResponse1.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(data);
        return builder;
    }

    /**
     * Class to build instances of {@link SystemsResponse1}.
     */
    public static class Builder {
        private System data;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  data  System value for data.
         */
        public Builder(System data) {
            this.data = data;
        }

        /**
         * Setter for data.
         * @param  data  System value for data.
         * @return Builder
         */
        public Builder data(System data) {
            this.data = data;
            return this;
        }

        /**
         * Builds a new {@link SystemsResponse1} object using the set fields.
         * @return {@link SystemsResponse1}
         */
        public SystemsResponse1 build() {
            return new SystemsResponse1(data);
        }
    }
}
