/*
 * SpaceTradersAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package io.spacetraders.alpha.v200.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;

/**
 * This is a model class for SystemsMarketsResponse type.
 */
public class SystemsMarketsResponse {
    private List<String> data;

    /**
     * Default constructor.
     */
    public SystemsMarketsResponse() {
    }

    /**
     * Initialization constructor.
     * @param  data  List of String value for data.
     */
    public SystemsMarketsResponse(
            List<String> data) {
        this.data = data;
    }

    /**
     * Getter for Data.
     * @return Returns the List of String
     */
    @JsonGetter("data")
    public List<String> getData() {
        return data;
    }

    /**
     * Setter for Data.
     * @param data Value for List of String
     */
    @JsonSetter("data")
    public void setData(List<String> data) {
        this.data = data;
    }

    /**
     * Converts this SystemsMarketsResponse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "SystemsMarketsResponse [" + "data=" + data + "]";
    }

    /**
     * Builds a new {@link SystemsMarketsResponse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link SystemsMarketsResponse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(data);
        return builder;
    }

    /**
     * Class to build instances of {@link SystemsMarketsResponse}.
     */
    public static class Builder {
        private List<String> data;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  data  List of String value for data.
         */
        public Builder(List<String> data) {
            this.data = data;
        }

        /**
         * Setter for data.
         * @param  data  List of String value for data.
         * @return Builder
         */
        public Builder data(List<String> data) {
            this.data = data;
            return this;
        }

        /**
         * Builds a new {@link SystemsMarketsResponse} object using the set fields.
         * @return {@link SystemsMarketsResponse}
         */
        public SystemsMarketsResponse build() {
            return new SystemsMarketsResponse(data);
        }
    }
}
