/*
 * SpaceTradersAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package io.spacetraders.alpha.v200.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;

/**
 * This is a model class for SystemsShipyardsShipsResponse type.
 */
public class SystemsShipyardsShipsResponse {
    private List<ShipyardListing> data;
    private Meta meta;

    /**
     * Default constructor.
     */
    public SystemsShipyardsShipsResponse() {
    }

    /**
     * Initialization constructor.
     * @param  data  List of ShipyardListing value for data.
     * @param  meta  Meta value for meta.
     */
    public SystemsShipyardsShipsResponse(
            List<ShipyardListing> data,
            Meta meta) {
        this.data = data;
        this.meta = meta;
    }

    /**
     * Getter for Data.
     * @return Returns the List of ShipyardListing
     */
    @JsonGetter("data")
    public List<ShipyardListing> getData() {
        return data;
    }

    /**
     * Setter for Data.
     * @param data Value for List of ShipyardListing
     */
    @JsonSetter("data")
    public void setData(List<ShipyardListing> data) {
        this.data = data;
    }

    /**
     * Getter for Meta.
     * @return Returns the Meta
     */
    @JsonGetter("meta")
    public Meta getMeta() {
        return meta;
    }

    /**
     * Setter for Meta.
     * @param meta Value for Meta
     */
    @JsonSetter("meta")
    public void setMeta(Meta meta) {
        this.meta = meta;
    }

    /**
     * Converts this SystemsShipyardsShipsResponse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "SystemsShipyardsShipsResponse [" + "data=" + data + ", meta=" + meta + "]";
    }

    /**
     * Builds a new {@link SystemsShipyardsShipsResponse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link SystemsShipyardsShipsResponse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(data, meta);
        return builder;
    }

    /**
     * Class to build instances of {@link SystemsShipyardsShipsResponse}.
     */
    public static class Builder {
        private List<ShipyardListing> data;
        private Meta meta;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  data  List of ShipyardListing value for data.
         * @param  meta  Meta value for meta.
         */
        public Builder(List<ShipyardListing> data, Meta meta) {
            this.data = data;
            this.meta = meta;
        }

        /**
         * Setter for data.
         * @param  data  List of ShipyardListing value for data.
         * @return Builder
         */
        public Builder data(List<ShipyardListing> data) {
            this.data = data;
            return this;
        }

        /**
         * Setter for meta.
         * @param  meta  Meta value for meta.
         * @return Builder
         */
        public Builder meta(Meta meta) {
            this.meta = meta;
            return this;
        }

        /**
         * Builds a new {@link SystemsShipyardsShipsResponse} object using the set fields.
         * @return {@link SystemsShipyardsShipsResponse}
         */
        public SystemsShipyardsShipsResponse build() {
            return new SystemsShipyardsShipsResponse(data, meta);
        }
    }
}
