/*
 * SpaceTradersAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package io.spacetraders.alpha.v200.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;

/**
 * This is a model class for Terms type.
 */
public class Terms {
    private String deadline;
    private Payment payment;
    private List<Deliver> deliver;

    /**
     * Default constructor.
     */
    public Terms() {
    }

    /**
     * Initialization constructor.
     * @param  deadline  String value for deadline.
     * @param  payment  Payment value for payment.
     * @param  deliver  List of Deliver value for deliver.
     */
    public Terms(
            String deadline,
            Payment payment,
            List<Deliver> deliver) {
        this.deadline = deadline;
        this.payment = payment;
        this.deliver = deliver;
    }

    /**
     * Getter for Deadline.
     * @return Returns the String
     */
    @JsonGetter("deadline")
    public String getDeadline() {
        return deadline;
    }

    /**
     * Setter for Deadline.
     * @param deadline Value for String
     */
    @JsonSetter("deadline")
    public void setDeadline(String deadline) {
        this.deadline = deadline;
    }

    /**
     * Getter for Payment.
     * @return Returns the Payment
     */
    @JsonGetter("payment")
    public Payment getPayment() {
        return payment;
    }

    /**
     * Setter for Payment.
     * @param payment Value for Payment
     */
    @JsonSetter("payment")
    public void setPayment(Payment payment) {
        this.payment = payment;
    }

    /**
     * Getter for Deliver.
     * @return Returns the List of Deliver
     */
    @JsonGetter("deliver")
    public List<Deliver> getDeliver() {
        return deliver;
    }

    /**
     * Setter for Deliver.
     * @param deliver Value for List of Deliver
     */
    @JsonSetter("deliver")
    public void setDeliver(List<Deliver> deliver) {
        this.deliver = deliver;
    }

    /**
     * Converts this Terms into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Terms [" + "deadline=" + deadline + ", payment=" + payment + ", deliver=" + deliver
                + "]";
    }

    /**
     * Builds a new {@link Terms.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Terms.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(deadline, payment, deliver);
        return builder;
    }

    /**
     * Class to build instances of {@link Terms}.
     */
    public static class Builder {
        private String deadline;
        private Payment payment;
        private List<Deliver> deliver;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  deadline  String value for deadline.
         * @param  payment  Payment value for payment.
         * @param  deliver  List of Deliver value for deliver.
         */
        public Builder(String deadline, Payment payment, List<Deliver> deliver) {
            this.deadline = deadline;
            this.payment = payment;
            this.deliver = deliver;
        }

        /**
         * Setter for deadline.
         * @param  deadline  String value for deadline.
         * @return Builder
         */
        public Builder deadline(String deadline) {
            this.deadline = deadline;
            return this;
        }

        /**
         * Setter for payment.
         * @param  payment  Payment value for payment.
         * @return Builder
         */
        public Builder payment(Payment payment) {
            this.payment = payment;
            return this;
        }

        /**
         * Setter for deliver.
         * @param  deliver  List of Deliver value for deliver.
         * @return Builder
         */
        public Builder deliver(List<Deliver> deliver) {
            this.deliver = deliver;
            return this;
        }

        /**
         * Builds a new {@link Terms} object using the set fields.
         * @return {@link Terms}
         */
        public Terms build() {
            return new Terms(deadline, payment, deliver);
        }
    }
}
