<?php

declare(strict_types=1);

/*
 * SpaceTradersAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpaceTradersAPILib\Models;

use stdClass;

class Cooldown implements \JsonSerializable
{
    /**
     * @var int
     */
    private $duration;

    /**
     * @var string
     */
    private $expiration;

    /**
     * @param int $duration
     * @param string $expiration
     */
    public function __construct(int $duration, string $expiration)
    {
        $this->duration = $duration;
        $this->expiration = $expiration;
    }

    /**
     * Returns Duration.
     */
    public function getDuration(): int
    {
        return $this->duration;
    }

    /**
     * Sets Duration.
     *
     * @required
     * @maps duration
     */
    public function setDuration(int $duration): void
    {
        $this->duration = $duration;
    }

    /**
     * Returns Expiration.
     */
    public function getExpiration(): string
    {
        return $this->expiration;
    }

    /**
     * Sets Expiration.
     *
     * @required
     * @maps expiration
     */
    public function setExpiration(string $expiration): void
    {
        $this->expiration = $expiration;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['duration']   = $this->duration;
        $json['expiration'] = $this->expiration;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
