<?php

declare(strict_types=1);

/*
 * SpaceTradersAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpaceTradersAPILib\Models;

use stdClass;

class Data5 implements \JsonSerializable
{
    /**
     * @var string
     */
    private $tradeSymbol;

    /**
     * @var int
     */
    private $units;

    /**
     * @param string $tradeSymbol
     * @param int $units
     */
    public function __construct(string $tradeSymbol, int $units)
    {
        $this->tradeSymbol = $tradeSymbol;
        $this->units = $units;
    }

    /**
     * Returns Trade Symbol.
     */
    public function getTradeSymbol(): string
    {
        return $this->tradeSymbol;
    }

    /**
     * Sets Trade Symbol.
     *
     * @required
     * @maps tradeSymbol
     */
    public function setTradeSymbol(string $tradeSymbol): void
    {
        $this->tradeSymbol = $tradeSymbol;
    }

    /**
     * Returns Units.
     */
    public function getUnits(): int
    {
        return $this->units;
    }

    /**
     * Sets Units.
     *
     * @required
     * @maps units
     */
    public function setUnits(int $units): void
    {
        $this->units = $units;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['tradeSymbol'] = $this->tradeSymbol;
        $json['units']       = $this->units;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
