<?php

declare(strict_types=1);

/*
 * SpaceTradersAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpaceTradersAPILib\Models;

use stdClass;

class Data12 implements \JsonSerializable
{
    /**
     * @var int
     */
    private $credits;

    /**
     * @var int
     */
    private $fuel;

    /**
     * @param int $credits
     * @param int $fuel
     */
    public function __construct(int $credits, int $fuel)
    {
        $this->credits = $credits;
        $this->fuel = $fuel;
    }

    /**
     * Returns Credits.
     */
    public function getCredits(): int
    {
        return $this->credits;
    }

    /**
     * Sets Credits.
     *
     * @required
     * @maps credits
     */
    public function setCredits(int $credits): void
    {
        $this->credits = $credits;
    }

    /**
     * Returns Fuel.
     */
    public function getFuel(): int
    {
        return $this->fuel;
    }

    /**
     * Sets Fuel.
     *
     * @required
     * @maps fuel
     */
    public function setFuel(int $fuel): void
    {
        $this->fuel = $fuel;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['credits'] = $this->credits;
        $json['fuel']    = $this->fuel;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
