<?php

declare(strict_types=1);

/*
 * SpaceTradersAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpaceTradersAPILib\Models;

use stdClass;

class Data2 implements \JsonSerializable
{
    /**
     * @var string[]|null
     */
    private $submitted;

    /**
     * Returns Submitted.
     *
     * @return string[]|null
     */
    public function getSubmitted(): ?array
    {
        return $this->submitted;
    }

    /**
     * Sets Submitted.
     *
     * @maps submitted
     *
     * @param string[]|null $submitted
     */
    public function setSubmitted(?array $submitted): void
    {
        $this->submitted = $submitted;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->submitted)) {
            $json['submitted'] = $this->submitted;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
