<?php

declare(strict_types=1);

/*
 * SpaceTradersAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpaceTradersAPILib\Models;

use stdClass;

class Data132 implements \JsonSerializable
{
    /**
     * @var Cooldown|null
     */
    private $cooldown;

    /**
     * @var Waypoint|null
     */
    private $waypoint;

    /**
     * Returns Cooldown.
     */
    public function getCooldown(): ?Cooldown
    {
        return $this->cooldown;
    }

    /**
     * Sets Cooldown.
     *
     * @maps cooldown
     */
    public function setCooldown(?Cooldown $cooldown): void
    {
        $this->cooldown = $cooldown;
    }

    /**
     * Returns Waypoint.
     */
    public function getWaypoint(): ?Waypoint
    {
        return $this->waypoint;
    }

    /**
     * Sets Waypoint.
     *
     * @maps waypoint
     */
    public function setWaypoint(?Waypoint $waypoint): void
    {
        $this->waypoint = $waypoint;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->cooldown)) {
            $json['cooldown'] = $this->cooldown;
        }
        if (isset($this->waypoint)) {
            $json['waypoint'] = $this->waypoint;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
