<?php

declare(strict_types=1);

/*
 * SpaceTradersAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpaceTradersAPILib\Models;

use stdClass;

class Data1 implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $token;

    /**
     * @var Agent|null
     */
    private $agent;

    /**
     * @var Faction|null
     */
    private $faction;

    /**
     * @var Contract|null
     */
    private $contract;

    /**
     * @var Ship|null
     */
    private $ship;

    /**
     * Returns Token.
     */
    public function getToken(): ?string
    {
        return $this->token;
    }

    /**
     * Sets Token.
     *
     * @maps token
     */
    public function setToken(?string $token): void
    {
        $this->token = $token;
    }

    /**
     * Returns Agent.
     */
    public function getAgent(): ?Agent
    {
        return $this->agent;
    }

    /**
     * Sets Agent.
     *
     * @maps agent
     */
    public function setAgent(?Agent $agent): void
    {
        $this->agent = $agent;
    }

    /**
     * Returns Faction.
     */
    public function getFaction(): ?Faction
    {
        return $this->faction;
    }

    /**
     * Sets Faction.
     *
     * @maps faction
     */
    public function setFaction(?Faction $faction): void
    {
        $this->faction = $faction;
    }

    /**
     * Returns Contract.
     */
    public function getContract(): ?Contract
    {
        return $this->contract;
    }

    /**
     * Sets Contract.
     *
     * @maps contract
     */
    public function setContract(?Contract $contract): void
    {
        $this->contract = $contract;
    }

    /**
     * Returns Ship.
     */
    public function getShip(): ?Ship
    {
        return $this->ship;
    }

    /**
     * Sets Ship.
     *
     * @maps ship
     */
    public function setShip(?Ship $ship): void
    {
        $this->ship = $ship;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->token)) {
            $json['token']    = $this->token;
        }
        if (isset($this->agent)) {
            $json['agent']    = $this->agent;
        }
        if (isset($this->faction)) {
            $json['faction']  = $this->faction;
        }
        if (isset($this->contract)) {
            $json['contract'] = $this->contract;
        }
        if (isset($this->ship)) {
            $json['ship']     = $this->ship;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
