<?php

declare(strict_types=1);

/*
 * SpaceTradersAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpaceTradersAPILib\Models;

use stdClass;

class Extraction implements \JsonSerializable
{
    /**
     * @var string
     */
    private $shipSymbol;

    /**
     * @var MYield
     */
    private $mYield;

    /**
     * @param string $shipSymbol
     * @param MYield $mYield
     */
    public function __construct(string $shipSymbol, MYield $mYield)
    {
        $this->shipSymbol = $shipSymbol;
        $this->mYield = $mYield;
    }

    /**
     * Returns Ship Symbol.
     */
    public function getShipSymbol(): string
    {
        return $this->shipSymbol;
    }

    /**
     * Sets Ship Symbol.
     *
     * @required
     * @maps shipSymbol
     */
    public function setShipSymbol(string $shipSymbol): void
    {
        $this->shipSymbol = $shipSymbol;
    }

    /**
     * Returns M Yield.
     */
    public function getMYield(): MYield
    {
        return $this->mYield;
    }

    /**
     * Sets M Yield.
     *
     * @required
     * @maps yield
     */
    public function setMYield(MYield $mYield): void
    {
        $this->mYield = $mYield;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['shipSymbol'] = $this->shipSymbol;
        $json['yield']      = $this->mYield;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
