<?php

declare(strict_types=1);

/*
 * SpaceTradersAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpaceTradersAPILib\Models;

use stdClass;

class MyShipsJettisonRequest implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $tradeSymbol;

    /**
     * @var int|null
     */
    private $units;

    /**
     * Returns Trade Symbol.
     */
    public function getTradeSymbol(): ?string
    {
        return $this->tradeSymbol;
    }

    /**
     * Sets Trade Symbol.
     *
     * @maps tradeSymbol
     */
    public function setTradeSymbol(?string $tradeSymbol): void
    {
        $this->tradeSymbol = $tradeSymbol;
    }

    /**
     * Returns Units.
     */
    public function getUnits(): ?int
    {
        return $this->units;
    }

    /**
     * Sets Units.
     *
     * @maps units
     */
    public function setUnits(?int $units): void
    {
        $this->units = $units;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->tradeSymbol)) {
            $json['tradeSymbol'] = $this->tradeSymbol;
        }
        if (isset($this->units)) {
            $json['units']       = $this->units;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
