<?php

declare(strict_types=1);

/*
 * SpaceTradersAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpaceTradersAPILib\Models;

use stdClass;

class MyShipsScanRequest implements \JsonSerializable
{
    /**
     * @var string
     */
    private $mode;

    /**
     * @param string $mode
     */
    public function __construct(string $mode)
    {
        $this->mode = $mode;
    }

    /**
     * Returns Mode.
     */
    public function getMode(): string
    {
        return $this->mode;
    }

    /**
     * Sets Mode.
     *
     * @required
     * @maps mode
     * @factory \SpaceTradersAPILib\Models\ModeEnum::checkValue
     */
    public function setMode(string $mode): void
    {
        $this->mode = $mode;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['mode'] = ModeEnum::checkValue($this->mode);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
