<?php

declare(strict_types=1);

/*
 * SpaceTradersAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SpaceTradersAPILib;

use SpaceTradersAPILib\Controllers;

/**
 * SpaceTradersAPILib client class
 */
class SpaceTradersAPIClient implements ConfigurationInterface
{
    private $ships;
    private $markets;
    private $trade;
    private $navigation;
    private $agents;
    private $contracts;
    private $extract;
    private $systems;
    private $shipyards;

    private $timeout = ConfigurationDefaults::TIMEOUT;
    private $enableRetries = ConfigurationDefaults::ENABLE_RETRIES;
    private $numberOfRetries = ConfigurationDefaults::NUMBER_OF_RETRIES;
    private $retryInterval = ConfigurationDefaults::RETRY_INTERVAL;
    private $backOffFactor = ConfigurationDefaults::BACK_OFF_FACTOR;
    private $maximumRetryWaitTime = ConfigurationDefaults::MAXIMUM_RETRY_WAIT_TIME;
    private $retryOnTimeout = ConfigurationDefaults::RETRY_ON_TIMEOUT;
    private $httpStatusCodesToRetry = ConfigurationDefaults::HTTP_STATUS_CODES_TO_RETRY;
    private $httpMethodsToRetry = ConfigurationDefaults::HTTP_METHODS_TO_RETRY;
    private $environment = ConfigurationDefaults::ENVIRONMENT;
    private $accessToken = ConfigurationDefaults::ACCESS_TOKEN;
    private $bearerAuthManager;
    private $authManagers = [];
    private $httpCallback;

    public function __construct(array $configOptions = null)
    {
        if (isset($configOptions['timeout'])) {
            $this->timeout = $configOptions['timeout'];
        }
        if (isset($configOptions['enableRetries'])) {
            $this->enableRetries = $configOptions['enableRetries'];
        }
        if (isset($configOptions['numberOfRetries'])) {
            $this->numberOfRetries = $configOptions['numberOfRetries'];
        }
        if (isset($configOptions['retryInterval'])) {
            $this->retryInterval = $configOptions['retryInterval'];
        }
        if (isset($configOptions['backOffFactor'])) {
            $this->backOffFactor = $configOptions['backOffFactor'];
        }
        if (isset($configOptions['maximumRetryWaitTime'])) {
            $this->maximumRetryWaitTime = $configOptions['maximumRetryWaitTime'];
        }
        if (isset($configOptions['retryOnTimeout'])) {
            $this->retryOnTimeout = $configOptions['retryOnTimeout'];
        }
        if (isset($configOptions['httpStatusCodesToRetry'])) {
            $this->httpStatusCodesToRetry = $configOptions['httpStatusCodesToRetry'];
        }
        if (isset($configOptions['httpMethodsToRetry'])) {
            $this->httpMethodsToRetry = $configOptions['httpMethodsToRetry'];
        }
        if (isset($configOptions['environment'])) {
            $this->environment = $configOptions['environment'];
        }
        if (isset($configOptions['accessToken'])) {
            $this->accessToken = $configOptions['accessToken'];
        }
        if (isset($configOptions['httpCallback'])) {
            $this->httpCallback = $configOptions['httpCallback'];
        }

        $this->bearerAuthManager = new BearerAuthManager($this->accessToken);
        $this->authManagers['global'] = $this->bearerAuthManager;
    }

    /**
     * Get the client configuration as an associative array
     */
    public function getConfiguration(): array
    {
        $configMap = [];

        if (isset($this->timeout)) {
            $configMap['timeout'] = $this->timeout;
        }
        if (isset($this->enableRetries)) {
            $configMap['enableRetries'] = $this->enableRetries;
        }
        if (isset($this->numberOfRetries)) {
            $configMap['numberOfRetries'] = $this->numberOfRetries;
        }
        if (isset($this->retryInterval)) {
            $configMap['retryInterval'] = $this->retryInterval;
        }
        if (isset($this->backOffFactor)) {
            $configMap['backOffFactor'] = $this->backOffFactor;
        }
        if (isset($this->maximumRetryWaitTime)) {
            $configMap['maximumRetryWaitTime'] = $this->maximumRetryWaitTime;
        }
        if (isset($this->retryOnTimeout)) {
            $configMap['retryOnTimeout'] = $this->retryOnTimeout;
        }
        if (isset($this->httpStatusCodesToRetry)) {
            $configMap['httpStatusCodesToRetry'] = $this->httpStatusCodesToRetry;
        }
        if (isset($this->httpMethodsToRetry)) {
            $configMap['httpMethodsToRetry'] = $this->httpMethodsToRetry;
        }
        if (isset($this->environment)) {
            $configMap['environment'] = $this->environment;
        }
        if ($this->bearerAuthManager->getAccessToken() !== null) {
            $configMap['accessToken'] = $this->bearerAuthManager->getAccessToken();
        }
        if (isset($this->httpCallback)) {
            $configMap['httpCallback'] = $this->httpCallback;
        }

        return $configMap;
    }

    /**
     * Clone this client and override given configuration options
     */
    public function withConfiguration(array $configOptions): self
    {
        return new self(\array_merge($this->getConfiguration(), $configOptions));
    }

    public function getTimeout(): int
    {
        return $this->timeout;
    }

    public function shouldEnableRetries(): bool
    {
        return $this->enableRetries;
    }

    public function getNumberOfRetries(): int
    {
        return $this->numberOfRetries;
    }

    public function getRetryInterval(): float
    {
        return $this->retryInterval;
    }

    public function getBackOffFactor(): float
    {
        return $this->backOffFactor;
    }

    public function getMaximumRetryWaitTime(): int
    {
        return $this->maximumRetryWaitTime;
    }

    public function shouldRetryOnTimeout(): bool
    {
        return $this->retryOnTimeout;
    }

    public function getHttpStatusCodesToRetry(): array
    {
        return $this->httpStatusCodesToRetry;
    }

    public function getHttpMethodsToRetry(): array
    {
        return $this->httpMethodsToRetry;
    }

    public function getEnvironment(): string
    {
        return $this->environment;
    }

    public function getBearerAuthCredentials(): ?BearerAuthCredentials
    {
        return $this->bearerAuthManager;
    }

    /**
     * Get the base uri for a given server in the current environment
     *
     * @param  string $server Server name
     *
     * @return string         Base URI
     */
    public function getBaseUri(string $server = Server::DEFAULT_): string
    {
        return static::ENVIRONMENT_MAP[$this->environment][$server];
    }

    /**
     * Returns Ships Controller
     */
    public function getShipsController(): Controllers\ShipsController
    {
        if ($this->ships == null) {
            $this->ships = new Controllers\ShipsController($this, $this->authManagers, $this->httpCallback);
        }
        return $this->ships;
    }

    /**
     * Returns Markets Controller
     */
    public function getMarketsController(): Controllers\MarketsController
    {
        if ($this->markets == null) {
            $this->markets = new Controllers\MarketsController(
                $this,
                $this->authManagers,
                $this->httpCallback
            );
        }
        return $this->markets;
    }

    /**
     * Returns Trade Controller
     */
    public function getTradeController(): Controllers\TradeController
    {
        if ($this->trade == null) {
            $this->trade = new Controllers\TradeController($this, $this->authManagers, $this->httpCallback);
        }
        return $this->trade;
    }

    /**
     * Returns Navigation Controller
     */
    public function getNavigationController(): Controllers\NavigationController
    {
        if ($this->navigation == null) {
            $this->navigation = new Controllers\NavigationController(
                $this,
                $this->authManagers,
                $this->httpCallback
            );
        }
        return $this->navigation;
    }

    /**
     * Returns Agents Controller
     */
    public function getAgentsController(): Controllers\AgentsController
    {
        if ($this->agents == null) {
            $this->agents = new Controllers\AgentsController(
                $this,
                $this->authManagers,
                $this->httpCallback
            );
        }
        return $this->agents;
    }

    /**
     * Returns Contracts Controller
     */
    public function getContractsController(): Controllers\ContractsController
    {
        if ($this->contracts == null) {
            $this->contracts = new Controllers\ContractsController(
                $this,
                $this->authManagers,
                $this->httpCallback
            );
        }
        return $this->contracts;
    }

    /**
     * Returns Extract Controller
     */
    public function getExtractController(): Controllers\ExtractController
    {
        if ($this->extract == null) {
            $this->extract = new Controllers\ExtractController(
                $this,
                $this->authManagers,
                $this->httpCallback
            );
        }
        return $this->extract;
    }

    /**
     * Returns Systems Controller
     */
    public function getSystemsController(): Controllers\SystemsController
    {
        if ($this->systems == null) {
            $this->systems = new Controllers\SystemsController(
                $this,
                $this->authManagers,
                $this->httpCallback
            );
        }
        return $this->systems;
    }

    /**
     * Returns Shipyards Controller
     */
    public function getShipyardsController(): Controllers\ShipyardsController
    {
        if ($this->shipyards == null) {
            $this->shipyards = new Controllers\ShipyardsController(
                $this,
                $this->authManagers,
                $this->httpCallback
            );
        }
        return $this->shipyards;
    }

    /**
     * A map of all baseurls used in different environments and servers
     *
     * @var array
     */
    private const ENVIRONMENT_MAP = [
        Environment::PRODUCTION => [
            Server::DEFAULT_ => 'https://v2-0-0.alpha.spacetraders.io',
        ],
    ];
}
